services:
  backend:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=5000
    volumes:
      - ./server:/main
      - ./server/content/media:/app/media:ro
    networks:
      - portfolio_shared_net

  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_BACKEND_URL=http://backend:5000
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./client/src/styles:/app/src/styles
    networks:
      - portfolio_shared_net

networks:
  portfolio_shared_net:
    external: true
